### PR TITLE
consistent name of env var

### PR DESCRIPTION
**Pull request by peterbe**
Consistency is nice and ALL project env vars should have a decent prefix. 

I think `CONTENT_ROOT` is allowed to be different because that's potentially the only one that's going to really matter for most people. 

CC @escattone

### CODE REVIEW

**Comment by Gregoor** [comment]
I'd argue that one is already prefixed with it's correct workspace, which is KS and not BUILD

**Comment by peterbe** [comment]
> I'd argue that one is already prefixed with it's correct workspace, which is KS and not BUILD

Technically, yes it's part of the `kumascript` workspace but that's very much an "implementation detail". It's conceptually part of the builder though.

**Comment by Gregoor** [comment]
For me the naming serves the purpose of specifiying where constants are used, which is implementation detail-y. So I both agree and disagree 😁

**Comment by peterbe** [comment]
I would still argue it's part of the builder and not kumascript for the following reasons:

- It's related to building pages. It's not related to testing or the server. 
- It's nice to have fewer general prefixes that multiple
- The original reason why `kumascript` is its own yarn workspace is because it got wholesale copied over and it had its own README and stuff. But if it wasn't for that legacy'ness it would have just been a module/sub-folder as part of the `build` workspace thing just like flaws is.

**Comment by Gregoor** [comment]
I have to be a bikeshedder here and say that I'm not sold on this rename yet. I think prefixes that point to their respective workspaces are a neat thing and I don't think we're drowning in them just yet. KS might exist out of organizational necessity but imo that holds for other workspaces too (in a NextJS world `client`, `ssr` and `server` would be a single workspace).

**Comment by peterbe** [comment]
So, there might a case of renaming all `BUILD_*`, `SERVER_*`, and `TESTING_*` to `YARI_*`. 
That's what I've used in the past on some Django server projects. But even there there are some exceptions like `REACT_APP_GOOGLE_ANALYTICS_ID` or `AWS_ACCESS_KEY_ID` or `EDITOR` which don't match the `MYPROJECT_` prefix. 

The ultimate fear is that there might be some env var that clashes with anything outside the Yari system. 

Onto the bikeshedding bandwagon, if we're going to keep the kumascript prefix, should it be `KUMASCRIPT_` instead? And the `envvars.md` file needs to be rearranged in terms of the `##` headings.

**Comment by escattone** [comment]
For me `BUILD_LIVE_SAMPLES_BASE_URL` feels more natural than `KS_LIVE_SAMPLES_BASE_URL` or `BUILD_KS_LIVE_SAMPLES_BASE_URL`, since I think of that setting as part of the builder, and I think of the `kumascript` workspace as an implementation detail of the build. My thinking is that the environment variables should be grouped according to how they're used at the highest level possible, so on the level of the builder and the server. So in other words, when I run the builder, I'd like to know what group of env vars I can set to control that process, and it'd be nice that they had a common prefix so it's easier to see them as a group.

**Pull request closed without merging**
